### ISSUE TITLE
0W on "current watt" only temperature values

### ISSUE THREAD

**Issue by pissa78** [lalelunet/measureit#24]
Hi, I recently installed measureit on Ubuntu server 16.04, but on the homepage only temperature's field is populated, other fileds are "0".
In "measureit.log" there is the following error recursively:

2016-11-08 10:22:11,277 ERROR Can not connect to the serial device: Traceback (most recent call last):
  File "/var/www/html/measureit/measureit_system_files/python/data-input.py", line 864, in <module>
    sensor_data_check( s, watt_sum, tmpr )
  File "/var/www/html/measureit/measureit_system_files/python/data-input.py", line 484, in sensor_data_check
    if sensor_settings[sensor]['scale_factor'] != 1:
KeyError: 0

Thanks a lot for your support.

**Comment by lalelunet** [comment]
Your USB cable is not connected as /dev/ttyUSB0 or /dev/ttyUSB1
You had to find out if your cable is connected and on which device.
 
https://github.com/lalelunet/measureit/wiki/Help---FAQ#does-my-system-support-the-usb-cable

And you can search for usb devices. You had to be root:

ls -la /dev/ | grep USB

This you should receive when it is connected as /dev/ttyUSB0:
crw-rw----  1 root dialout 188,   0 Oct 10 17:06 ttyUSB0

**Comment by pissa78** [comment]
I tried to execute the grabber in debug mode from cli and this is the output:


`<msg><src>CC128-v1.44</src><dsb>01461</dsb><time>09:39:56</time><tmpr>18.3</tmpr><sensor>0</sensor><id>00864</id><type>1</type><ch1><watts>00693</watts></ch1></msg>`

`<msg><src>CC128-v1.44</src><dsb>01461</dsb><time>09:40:02</time><tmpr>18.3</tmpr><sensor>0</sensor><id>00864</id><type>1</type><ch1><watts>00677</watts></ch1></msg>`

`<msg><src>CC128-v1.44</src><dsb>01461</dsb><time>09:40:08</time><tmpr>18.3</tmpr><sensor>0</sensor><id>00864</id><type>1</type><ch1><watts>00685</watts></ch1></msg>`

`<msg><src>CC128-v1.44</src><dsb>01461</dsb><time>09:40:14</time><tmpr>18.3</tmpr><sensor>0</sensor><id>00864</id><type>1</type><ch1><watts>00680</watts></ch1></msg>`

`<msg><src>CC128-v1.44</src><dsb>01461</dsb><time>09:40:20</time><tmpr>18.3</tmpr><sensor>0</sensor><id>00864</id><type>1</type><ch1><watts>00679</watts></ch1></msg>`



So I think that the cable is correctly connected and the device is /dev/ttyUSB0.
Following there is the measureit.log file:



2016-11-09` 09:39:25,593 INFO Try to connect to the serial device /dev/ttyUSB0
2016-11-09 09:39:25,602 INFO Connected to the serial device /dev/ttyUSB0
2016-11-09 09:39:25,603 INFO Try to parse config file in config_parse
2016-11-09 09:39:25,603 INFO Parsing config file successful
2016-11-09 09:39:25,603 DEBUG {'database_user': 'measureit', 'database_name': 'measure_it', 'database_passwd': 'measureitpasswd', 'database_host': 'localhost', 'database_port': '3306'}
2016-11-09 09:39:25,603 INFO Try to get sensor list in sensor_list_get
2016-11-09 09:39:25,616 DEBUG Try to execute query: SELECT sensor_id FROM measure_sensors
2016-11-09 09:39:25,617 INFO Get sensor in sensor_list_get Sensor: 0
2016-11-09 09:39:25,617 INFO Get sensor in sensor_list_get Sensor: 1
2016-11-09 09:39:25,617 INFO Get sensor in sensor_list_get Sensor: 2
2016-11-09 09:39:25,617 INFO Get sensor in sensor_list_get Sensor: 3
2016-11-09 09:39:25,617 INFO Get sensor list successful
2016-11-09 09:39:25,617 DEBUG {0: {'watt': 0, 'pvoutput_watt_sum': {}, 'counter': 0, 'pvoutput_batch_string': {}, 'tmpr': 0}, 1: {'watt': 0, 'pvoutput_watt_sum': {}, 'counter': 0, 'pvoutput_batch_string': {}, 'tmpr': 0}, 2: {'watt': 0, 'pvoutput_watt_sum': {}, 'counter': 0, 'pvoutput_batch_string': {}, 'tmpr': 0}, 3: {'watt': 0, 'pvoutput_watt_sum': {}, 'counter': 0, 'pvoutput_batch_string': {}, 'tmpr': 0}}
2016-11-09 09:39:25,617 INFO Try to get systems settings in system_settings_get
2016-11-09 09:39:25,618 DEBUG Try to execute query: SELECT measure_system_setting_name, measure_system_setting_value FROM measure_system
2016-11-09 09:39:25,618 INFO Get system settings successful
2016-11-09 09:39:25,618 DEBUG {'system_settings_tmpr': 'c', 'database_name': 'measure_it', 'language_use': 'en_EN', 'system_settings_system': 'envi', 'system_settings_data_save_type': '0', 'database_port': '3306', 'current_version': '118', 'database_passwd': 'measureitpasswd', 'database_host': 'localhost', 'database_user': 'measureit'}
2016-11-09 09:39:25,618 INFO Try to get sensor settings from sensor_settings_get
2016-11-09 09:39:25,619 DEBUG Try to execute query: SELECT * FROM measure_settings
2016-11-09 09:39:25,619 INFO Get sensor settings successful
2016-11-09 09:39:25,619 DEBUG {}
2016-11-09 09:39:25,619 DEBUG No twitter settings found. Twitter notifications will not be used
2016-11-09 09:39:25,619 DEBUG No email settings found. Email notifications will not be used
2016-11-09 09:39:25,619 DEBUG No notification settings found. Notifications will not be used
2016-11-09 09:39:25,619 INFO Try to run hourly job in cron_timer_hourly
2016-11-09 09:39:25,619 DEBUG Make hourly usage from day_from to day_to: 2016-11-9
2016-11-09 09:39:25,619 DEBUG Make hourly usage from hour_from_from to hour_to in utc time: 7 - 8
2016-11-09 09:39:25,622 DEBUG Try to execute query: select sensor, data, unix_timestamp(time) from measure_watt where time between '2016-11-9 7:00:00' AND '2016-11-9 8:00:00' AND sensor=0
2016-11-09 09:39:25,622 DEBUG Try to execute query: INSERT IGNORE INTO measure_watt_hourly ( sensor, data, hour, time ) VALUES ( "0", "0", "7", "2016-11-9" )
2016-11-09 09:39:25,623 DEBUG Execute query successful
2016-11-09 09:39:25,623 WARNING Error in cron_timer_hourly. Error: Traceback (most recent call last):
  File "/var/www/html/measureit/measureit_system_files/python/data-input.py", line 164, in cron_timer_hourly
    sensor_notifications_cron_check(sensor, sensor_settings[sensor]['notifications'])
KeyError: 0

2016-11-09 09:39:25,623 DEBUG Critical system error occured
2016-11-09 09:39:25,623 DEBUG Alert Message will send at 5000. Current counter is now: 1
2016-11-09 09:39:25,624 INFO Try to run daily job in cron_timer_daily
2016-11-09 09:39:25,624 INFO Try to run about all sensors
2016-11-09 09:39:25,624 INFO Found Sensor 0
2016-11-09 09:39:25,624 DEBUG Try to execute query: select sensor, data, unix_timestamp(time) from measure_watt where time between '2016-11-08 00:00:00' AND '2016-11-09 00:00:00' AND sensor=0
2016-11-09 09:39:25,625 INFO Read data from sensor: 0
2016-11-09 09:39:25,625 DEBUG Try to execute query: INSERT IGNORE INTO measure_watt_daily ( sensor, data, time ) VALUES ( "0", "0", "2016-11-08 00:00:00" )
2016-11-09 09:39:25,626 DEBUG Execute query successful
2016-11-09 09:39:25,626 INFO Sensor data successful collected from sensor: 0
2016-11-09 09:39:25,626 INFO Try to delete old data from sensor: 0
2016-11-09 09:39:25,626 INFO Found Sensor 1
2016-11-09 09:39:25,626 DEBUG Try to execute query: select sensor, data, unix_timestamp(time) from measure_watt where time between '2016-11-08 00:00:00' AND '2016-11-09 00:00:00' AND sensor=1
2016-11-09 09:39:25,627 INFO Read data from sensor: 1
2016-11-09 09:39:25,627 DEBUG Try to execute query: INSERT IGNORE INTO measure_watt_daily ( sensor, data, time ) VALUES ( "1", "0", "2016-11-08 00:00:00" )
2016-11-09 09:39:25,627 DEBUG Execute query successful
2016-11-09 09:39:25,628 INFO Sensor data successful collected from sensor: 1
2016-11-09 09:39:25,628 INFO Try to delete old data from sensor: 1
2016-11-09 09:39:25,628 INFO Found Sensor 2
2016-11-09 09:39:25,628 DEBUG Try to execute query: select sensor, data, unix_timestamp(time) from measure_watt where time between '2016-11-08 00:00:00' AND '2016-11-09 00:00:00' AND sensor=2
2016-11-09 09:39:25,628 INFO Read data from sensor: 2
2016-11-09 09:39:25,629 DEBUG Try to execute query: INSERT IGNORE INTO measure_watt_daily ( sensor, data, time ) VALUES ( "2", "0", "2016-11-08 00:00:00" )
2016-11-09 09:39:25,629 DEBUG Execute query successful
2016-11-09 09:39:25,629 INFO Sensor data successful collected from sensor: 2
2016-11-09 09:39:25,629 INFO Try to delete old data from sensor: 2
2016-11-09 09:39:25,629 INFO Found Sensor 3
2016-11-09 09:39:25,630 DEBUG Try to execute query: select sensor, data, unix_timestamp(time) from measure_watt where time between '2016-11-08 00:00:00' AND '2016-11-09 00:00:00' AND sensor=3
2016-11-09 09:39:25,630 INFO Read data from sensor: 3
2016-11-09 09:39:25,631 DEBUG Try to execute query: INSERT IGNORE INTO measure_watt_daily ( sensor, data, time ) VALUES ( "3", "0", "2016-11-08 00:00:00" )
2016-11-09 09:39:25,631 DEBUG Execute query successful
2016-11-09 09:39:25,631 INFO Sensor data successful collected from sensor: 3
2016-11-09 09:39:25,631 INFO Try to delete old data from sensor: 3
2016-11-09 09:39:25,632 INFO Try to run weekly job in cron_timer_weekly
2016-11-09 09:39:25,993 INFO Update: No new version found
2016-11-09 09:39:25,993 INFO weekly job in cron_timer_weekly successful
2016-11-09 09:39:25,994 INFO Look if I should restart
2016-11-09 09:39:25,994 INFO No restart file found
2016-11-09 09:39:25,994 INFO Start parsing XML
2016-11-09 09:39:27,048 DEBUG No clamps found on sensor 0
2016-11-09 09:39:27,049 DEBUG Try to execute query: UPDATE measure_data_now SET tmpr = "18.3" WHERE sensor_id = 0
2016-11-09 09:39:27,049 DEBUG Execute query successful
2016-11-09 09:39:27,050 DEBUG Try to execute query: INSERT INTO measure_tmpr ( data, time ) values( "18.3", UTC_TIMESTAMP( ) ) 
2016-11-09 09:39:27,050 DEBUG Execute query successful
2016-11-09 09:39:27,051 DEBUG Try to execute query: INSERT IGNORE INTO measure_tmpr_hourly ( data, time, hour ) VALUES ( "18.3", UTC_TIMESTAMP( ), "8" )
2016-11-09 09:39:27,051 DEBUG Execute query successful
2016-11-09 09:39:27,051 ERROR Can not connect to the serial device: Traceback (most recent call last):
  File "/var/www/html/measureit/measureit_system_files/python/data-input.py", line 864, in <module>
    sensor_data_check( s, watt_sum, tmpr )
  File "/var/www/html/measureit/measureit_system_files/python/data-input.py", line 484, in sensor_data_check
    if sensor_settings[sensor]['scale_factor'] != 1:
KeyError: 0

2016-11-09 09:39:27,051 DEBUG Critical system error occured
2016-11-09 09:39:27,051 DEBUG Alert Message will send at 5000. Current counter is now: 2
2016-11-09 09:39:33,009 DEBUG No clamps found on sensor 0
2016-11-09 09:39:33,009 ERROR Can not connect to the serial device: Traceback (most recent call last):
  File "/var/www/html/measureit/measureit_system_files/python/data-input.py", line 864, in <module>
    sensor_data_check( s, watt_sum, tmpr )
  File "/var/www/html/measureit/measureit_system_files/python/data-input.py", line 484, in sensor_data_check
    if sensor_settings[sensor]['scale_factor'] != 1:
KeyError: 0

**Comment by lalelunet** [comment]
It seems that the connection breaks after some time. There is a connection at start. The grabber gets some data and insert them into the database.

Can you start the grabber again and open a second terminal and take a look at the systemlog with:
sudo journalctl -f

There must be a reason why the device is disconnected. 

It is disconnected?
ls -la /dev/ | grep USB

**Comment by pissa78** [comment]
I restarted the grabber and this is the output of sudo journalctl -f:

```
Nov 13 12:43:10 Pissa-Server sudo[24333]:    pissa : TTY=pts/0 ; PWD=/home/pissa ; USER=root ; COMMAND=/usr/bin/python /var/www/html/measureit/measureit_system_files/python/data-input.py debug v
Nov 13 12:43:10 Pissa-Server sudo[24333]: pam_unix(sudo:session): session opened for user root by pissa(uid=0)
Nov 13 12:43:28 Pissa-Server sudo[24345]:    pissa : TTY=pts/1 ; PWD=/home/pissa ; USER=root ; COMMAND=/bin/journalctl -f
```

and nothing else about the grabber or USB...

The device is connected: 

```
ls -la /dev/ | grep USB
crw-rw----  1 root dialout 188,   0 Nov  9 09:31 ttyUSB0
```

and this is the output of the grabber:

```
<msg><src>CC128-v1.44</src><dsb>01465</dsb><time>12:50:56</time><tmpr>18.1</tmpr><sensor>0</sensor><id>00864</id><type>1</type><ch1><watts>00937</watts></ch1></msg>
<msg><src>CC128-v1.44</src><dsb>01465</dsb><time>12:50:58</time><tmpr>18.1</tmpr><sensor>1</sensor><id>00750</id><type>1</type><ch1><watts>00073</watts></ch1></msg>
<msg><src>CC128-v1.44</src><dsb>01465</dsb><time>12:51:00</time><tmpr>18.1</tmpr><sensor>2</sensor><id>01395</id><type>1</type><ch1><watts>00076</watts></ch1></msg>
<msg><src>CC128-v1.44</src><dsb>01465</dsb><time>12:51:02</time><tmpr>18.1</tmpr><sensor>0</sensor><id>00864</id><type>1</type><ch1><watts>00726</watts></ch1></msg>

```

**Comment by lalelunet** [comment]
This is a strange behavier. This seems to working as expected.

Do you create a position on the sensor 0 and 1 in the admin interface?

**Comment by pissa78** [comment]
Yes... I created a position for sensor 0 1 and 2...

**Comment by lalelunet** [comment]
Do you get any data in the front end graphs? Regardless of which one

**Comment by pissa78** [comment]
No data in the graph...
Following there is the screenshot of the homepage...

![screenshot_measureit](https://cloud.githubusercontent.com/assets/23333290/20298972/0285c920-ab19-11e6-8ee5-1d74c0289299.png)

**Comment by pissa78** [comment]
In the last days I tried a complete reinstall of "measureit" and now it seems to working fine.
Thanks a lot for your support.

**Comment by lalelunet** [comment]
Sorry for not answering so long. Currently there is a lot of "real life" work :)

It is good that everything is working now as expected. Did you realize a different from the first install?
